### ISSUE TITLE
ffmpeg-php .configure error

### ISSUE THREAD

**Issue by rivai1** [hostsoft/ffmpeginstaller#1]
when i try ./configure error no ffmpeg header found. How to fix this issue ..?

**Comment by ninetian** [comment]
what you install?
this only install ffmpeg without ffmpeg-php

sorry, i am not find this error
my tested OS CentOS 7 64 bit and deloly over 50+ servers not any error

**Comment by ninetian** [comment]
https://github.com/tony2001/ffmpeg-php/issues/24
this ?
