### ISSUE TITLE
mplayer failed install

### ISSUE THREAD

**Issue by spirogg** [hostsoft/ffmpeginstaller#3]
hi i get all the way to mplayer installation then get mplayer failed to install

then that's it 

centos7 with cpanel/whm latest version

any idea why and how to fix this

**Comment by ninetian** [comment]
what you see?

**Comment by ninetian** [comment]
Try

> INSTALL_SDIR='/usr/src/ffmpegscript'
> SOURCE_URL='http://mirror.ffmpeginstaller.com/source/mplayer'
> INSTALL_DDIR='/usr/local/cpffmpeg'
> export cpu=`cat "/proc/cpuinfo" | grep "processor"|wc -l`
> export TMPDIR=$HOME/tmp
> cd $INSTALL_SDIR/
> rm -rf mplayer*
> 
> wget http://www.mplayerhq.hu/MPlayer/releases/MPlayer-1.3.0.tar.xz
> tar xJfv MPlayer-1.3.0.tar.xz
> cd MPlayer-1.3.0
> ./configure --prefix=$INSTALL_DDIR  --codecsdir=$INSTALL_DDIR/lib/codecs/   \
> 		--extra-cflags=-I/usr/local/cpffmpeg/include/ --extra-ldflags=-L/usr/local/cpffmpeg/lib \
> 		--with-freetype-config=/usr/local/cpffmpeg/bin/freetype-config   --yasm=/usr/local/cpffmpeg/bin/yasm
> make -j$cpu
> make install



tell me what you see fail and give error logs

**Comment by spirogg** [comment]
tried not working and i don't know where log is, how much you charge me to set this up ? i want to use clipbucket.com script and nneds a few things with ffmpeg etc

thanks

spiro

**Comment by ninetian** [comment]
Hi

Please give root ssh info, i try help install and check test it
if you need help install clipbucket video scripts, please email the zip pack
i can try help deploy it

info send to  ****
email title = ffmpeg

fee is free

**Comment by spirogg** [comment]
Thank you I sent root and password and clipbucket zip file plus another email with links to settings in clipbucket I installed already but not sure if correct. Been a long time for me.

Thank you so much. I am up and awaiting your email if you need anything. From me.

**Comment by ninetian** [comment]
i have reply you email
i think the you are not clear OS to install the scripts
maybe use other scripts first, so it's not work
i check most fail, but you ffmpeg is work

so i can fix, that's need long times

maybe can reinstall OS i can help deploy it

**Comment by spirogg** [comment]
ok i will redeploy vps but what i use centos 7 or centos 6 latest ?? and do they install mariadb or mysql ? please give me instructions to give to them please what we need for OS ubuntu Centos and what version and do we need anything else install or we can do the rest ?

please let me know I am writing to support right now ?
