### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by nirupamarya** [hostsoft/ffmpeginstaller#4]
Nothing to do
sh: tools_freetype.sh: No such file or directory
sh: tools_ynasm.sh: No such file or directory
sh: vc_flvtool2.sh: No such file or directory
sh: vc_yamdi.sh: No such file or directory
sh: vc_mp4box.sh: No such file or directory
sh: ac_libwmf.sh: No such file or directory
sh: ac_liblame.sh: No such file or directory
sh: ac_libogg.sh: No such file or directory
sh: ac_liboggz.sh: No such file or directory
sh: ac_libamrnbwb.sh: No such file or directory
sh: ac_libopencoreamr.sh: No such file or directory
sh: ac_liba52.sh: No such file or directory
sh: ac_libflac.sh: No such file or directory
sh: ac_libfaad2.sh: No such file or directory
sh: ac_libfdkaac.sh: No such file or directory
sh: ac_libvoaacenc.sh: No such file or directory
sh: ac_libvoamrwbenc.sh: No such file or directory
sh: ac_libneroaacenc.sh: No such file or directory
sh: ac_libao.sh: No such file or directory
sh: ac_libspeex.sh: No such file or directory
sh: ac_libvorbistools.sh: No such file or directory
sh: ac_libvorbis.sh: No such file or directory
sh: ac_libfishsound.sh: No such file or directory
sh: ac_libopus.sh: No such file or directory
sh: vc_libtheora.sh: No such file or directory
sh: vc_xvid.sh: No such file or directory
sh: vc_x264.sh: No such file or directory
sh: vc_x265.sh: No such file or directory
sh: vc_mplayer_codecs.sh: No such file or directory
sh: vc_mplayer.sh: No such file or directory
sh: vc_ffmpeg.sh: No such file or directory
Create Links
All is Done
That's Path
/usr/bin/ffmpeg
/usr/bin/ffprobe
which: no qt-faststart in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
which: no mplayer in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
which: no mencoder in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/local/bin/flvtool2
which: no MP4Box in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
which: no yamdi in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/local/bin/mediainfo
which: no neroAacEnc in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/bin/x264
which: no x265 in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
ImageMagick Command Path
/usr/bin/identify
/usr/bin/convert

**Comment by ninetian** [comment]
sorry, the latest i am not testing
wait please

**Comment by nirupamarya** [comment]
have you checked.

**Comment by ninetian** [comment]
fix
please re-clone and run it

Thanks.

**Comment by nirupamarya** [comment]
the problem is same.

**Comment by ninetian** [comment]
delete all
run git clone again

the path has fix

**Comment by ninetian** [comment]
Sorry, i have tested,  OK now

**Comment by nirupamarya** [comment]
there is one problem. its saying no ffmpeg check here:
which {ffmpeg,ffprobe,qt-faststart,mplayer,mencoder,flvtool2,MP4Box,yamdi,mediainfo,neroAacEnc,x264,x265}
/usr/bin/which: no ffmpeg in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/bin/which: no ffprobe in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/bin/which: no qt-faststart in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/local/bin/mplayer
/usr/local/bin/mencoder
/usr/local/bin/flvtool2
/usr/local/bin/MP4Box
/usr/local/bin/yamdi
/usr/local/bin/mediainfo
/usr/local/bin/neroAacEnc
/usr/local/bin/x264
/usr/local/bin/x265

**Comment by ninetian** [comment]
Hi
sorry, the libvpx bug has fix
i has been use linode vps to full tested, all work


[root@li1641-172 ffmpeg]# which {ffmpeg,ffprobe,qt-faststart,mplayer,mencoder,flvtool2,MP4Box,yamdi,mediainfo,neroAacEnc,x264,x265}

/usr/local/bin/ffmpeg
/usr/local/bin/ffprobe
/usr/local/bin/qt-faststart
/usr/local/bin/mplayer
/usr/local/bin/mencoder
/usr/local/bin/flvtool2
/usr/local/bin/MP4Box
/usr/local/bin/yamdi
/usr/local/bin/mediainfo
/usr/local/bin/neroAacEnc
/usr/local/bin/x264
/usr/local/bin/x265

**Comment by nirupamarya** [comment]
can you please provide me old version. Installation is successful. but some function is not working in ffmpeg. if you can provide me old version installation link then it will be better.

**Comment by ninetian** [comment]
sorry, what function not work?
the ffmpeg not the version difference

because of repeated installation
maybe you need manually modified the /etc/ld.so.conf file
remove extra this
```
/usr/lib
/usr/lib64
/usr/local/lib
/usr/local/lib64
/usr/local/ffmpegtoolkit/lib
/usr/local/ffmpegtoolkit/lib64
```
but keep one, and run 
`ldconfig`

run shell

![ffmpegcheck](https://user-images.githubusercontent.com/2613794/36603157-e1b8385e-18f4-11e8-8fa3-001b63161c14.jpg)

if show this all is work
![ffmpegcheck](https://user-images.githubusercontent.com/2613794/36603274-3ab5df06-18f5-11e8-8ed1-9d0f6d3da820.jpg)


to check

**Comment by nirupamarya** [comment]
again its same problem.

which: no ffmpeg in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
which: no ffprobe in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
which: no qt-faststart in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/local/bin/mplayer
/usr/local/bin/mencoder
/usr/local/bin/flvtool2
/usr/local/bin/MP4Box
/usr/local/bin/yamdi
/usr/local/bin/mediainfo
/usr/local/bin/neroAacEnc
/usr/local/bin/x264
/usr/local/bin/x265
ImageMagick Command Path
/usr/bin/identify
/usr/bin/convert

**Comment by nirupamarya** [comment]
hey please look into this. Its giving same error again.

**Comment by ninetian** [comment]
has fix cPanel problem and has been tested
