### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by nirupamarya** [hostsoft/ffmpeginstaller#5]
again its same problem.

which: no ffmpeg in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
which: no ffprobe in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
which: no qt-faststart in (/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
/usr/local/bin/mplayer
/usr/local/bin/mencoder
/usr/local/bin/flvtool2
/usr/local/bin/MP4Box
/usr/local/bin/yamdi
/usr/local/bin/mediainfo
/usr/local/bin/neroAacEnc
/usr/local/bin/x264
/usr/local/bin/x265
ImageMagick Command Path
/usr/bin/identify
/usr/bin/convert

**Comment by ninetian** [comment]
Hi
i am busy
the depend package download url in https://sourceforge.net
but i have test sometime sourceforge.net download servers down and return "Maintenance and overload info"
so downloaded package is empty, cause install fail.
maybe clone all depend software file storage in github can resolve,
if I'm have free times , i will do it

Thanks


just run again, i have fix some problem.

```
yum install git wget -y 
cd /opt
rm -rf ffmpegtoolkit
git clone https://github.com/hostsoft/ffmpegtoolkit.git ffmpegtoolkit
cd ffmpegtoolkit
sh latest.sh
```
