### ISSUE TITLE
hi after restart server my script no longer recongnize ffmpeg ? 

### ISSUE THREAD

**Issue by spirogg** [hostsoft/ffmpeginstaller#6]
hi first off I wanted to say thank you for creating this...

I just have one issue, After installing it seems like either in cPanel In initially installed centos 7 then opted for cloudlinux 7 then added ffmpeg but it stays alive for a bit until I either restart server or apache?
Then my script doesn't recognize where ffmpeg is, even though I have added /user/local/bin/ffmpeg ffprobe etc etc... clipbucket.com is the script I am trying to use, so not 100% what the issue is - 
but seems either its apache restart, server restart or selecting php muti changer to change settings in php ini like max upload size etc etc..

last time I ran ffmpeg it said cant locate libavdevice58 and some more 

so now I am deleting the folder and everything in it to re-install from your script.

 but how would I make it that it stays always active in my script ? ldconfig ? 

any shed of light would be awesome thank you so much again

Spiro

**Comment by spirogg** [comment]
here is the error i got after reinstall and restart server ?

ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory

**Comment by spirogg** [comment]
server1:~# ldd $(which ffmpeg)
        linux-vdso.so.1 =>  (0x00007ffd8ed3a000)
        libavdevice.so.58 => not found
        libavfilter.so.7 => not found
        libavformat.so.58 => not found
        libavcodec.so.58 => not found
        libpostproc.so.55 => not found
        libswresample.so.3 => not found
        libswscale.so.5 => not found
        libavutil.so.56 => not found
        libm.so.6 => /lib64/libm.so.6 (0x00007f9faadfa000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9faabde000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9faa81b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9fab0fc000)

**Comment by ninetian** [comment]
try
`ldconfig`

check again

**Comment by spirogg** [comment]
Tred again but same thing. ?? Is there a way for me to.uninstall properly. ?? I just deleted folders and then tried reinstall. But I get same thing. Even after doing ldconfig. Is there proper way to install ffmpeg etc. And reinstall. And do I do ldconfig server1~/  
Or do I have to do it right after it finish install. I can see /user/lib64 has libavdevice.56 bot no where there .58

**Comment by spirogg** [comment]
i tried uninstall but still i get these errors ? can i reinstall this do I need to create different directory ? then try to install, I dont think it overwrites files so its not adding the lib files i need ??

**Comment by spirogg** [comment]
there is no way to uninstall this and then reinstall. never works out ?

**Comment by ninetian** [comment]
please sure
#1 you are use CentOS 7.*  64bit mini or full install, it's new install
#### not have try other same script install ffmpeg

#2 SELinux has disable
#3 run the shell used root account

You problem i think you install different version related dependence


if you want remote, just use
```
array=( /lib /usr/lib /usr/local/lib /lib64 /usr/lib64 /usr/local/lib64  )
for i in "${array[@]}"
do
echo "Start Remove......"
rm -rf "$i/liba52*"
rm -rf "$i//libamr*"
rm -rf "$i//libavcodec*"
rm -rf "$i//libavformat*"
rm -rf "$i//libavutil*"
rm -rf "$i//libdha*"
rm -rf "$i//libfaac*"
rm -rf "$i//libfaad*"
rm -rf "$i//libmp3lame*"
rm -rf "$i//libmp4v2*"
rm -rf "$i//libogg*"
rm -rf "$i//libtheora*"
rm -rf "$i//libvorbis*"
echo "Remove Done!"
done

array=( /bin /usr/bin /usr/local/bin  )
for i in "${array[@]}"
do
echo "Start Remove......"
rm -rf "$i/ffmpeg"
rm -rf "$i/mplayer"
rm -rf "$i/mencoder"
rm -rf "$i/flvtool2"
echo "Remove Done!"
done

rm -rf /opt/ffmpegtoolkit
rm -rf /usr/local/ffmpegtoolkit
rm -rf ~/tmp
mkdir -p ~/tmp

```

**Comment by ninetian** [comment]
and don't try use it in VPS,  has most problem of limit

**Comment by spirogg** [comment]
working
