### ISSUE TITLE
is there a way to make a static build of this to just upload in opt/myffmpeg/ffmpeg or similar ?

### ISSUE THREAD

**Issue by spirogg** [hostsoft/ffmpeginstaller#7]
is there a way to make a static build of this to just upload in opt/myffmpeg/ffmpeg or a similar folder i can upload to and all codecs etc etc will be ready - just point to that directory and it works ?

**Comment by spirogg** [comment]
fdk_aac and x264 is what clipbucket.com script uses.. 

FFMPEG Path 
/usr/local/bin/ffmpeg


 PHP Path 
/usr/local/bin/php
 

MP4Box Path 
/usr/local/bin/MP4Box
 
FFprobe Path 
/usr/local/bin/ffprobe


Media Info Path 
/usr/local/bin/mediainfo


Imagick Path 
/usr/bin/convert

Mplayer Path 
/usr/local/bin/mplayer


Mplayer info Max videos to convert at once 
2

Max time wait after max processess 
7200


this is what the settings look like in clipbucket script 
would be awesome to have static build with all these or just show me how to setup so when restart server or change php version or restart apache doesnt affect ffmpeg and codecs will still work at /usr/local/bin/ffmpeg ffprobe MP4Box etc etc

thank you

**Comment by spirogg** [comment]
server1:~# ldd $(which ffmpeg)
        linux-vdso.so.1 =>  (0x00007ffd8ed3a000)
        libavdevice.so.58 => not found
        libavfilter.so.7 => not found
        libavformat.so.58 => not found
        libavcodec.so.58 => not found
        libpostproc.so.55 => not found
        libswresample.so.3 => not found
        libswscale.so.5 => not found
        libavutil.so.56 => not found
        libm.so.6 => /lib64/libm.so.6 (0x00007f9faadfa000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9faabde000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9faa81b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9fab0fc000)

**Comment by ninetian** [comment]
sorry
if you want use static
just try this
https://johnvansickle.com/ffmpeg/
this static pack

just unpack can use


this project most use to custom.
