### ISSUE TITLE
how can we upgrade ffmpeg to a version other than N-90713-g955fa237f4

### ISSUE THREAD

**Issue by spirogg** [hostsoft/ffmpeginstaller#8]
ffmpeg version N-90713-g955fa237f4 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-16)

**Comment by spirogg** [comment]
what about upgrade ffmpeg to ffmpeg version 3.3.2

**Comment by ninetian** [comment]
you can try reinstall os and reinstall ffmpeg
install scripts clone the latest ffmpeg GIT versions
if you now install, the FFMPEG is 4.0 versions

if you want custom version
edit the vc_ffmpeg.sh

find
`	git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg`
change to 
`	git clone -b 'n4.0' --single-branch --depth 1 https://github.com/FFmpeg/FFmpeg.git ffmpeg`

reinstall 

the n4.0 is versions tag
you can find it in  https://github.com/FFmpeg/FFmpeg/tags
EG: you like 3.* , just replace **n4.0** to **n3.37**


have a nice day....

**Comment by ninetian** [comment]
fix
