### ISSUE TITLE
hi not working any more I see error resolving namedirectory.com or namedir.com

### ISSUE THREAD

**Issue by spirogg** [hostsoft/ffmpeginstaller#9]
hi i installed again on another server and ffmpeg not work when trying to use. while installing ai saw an error that said trying to resolve host namedir.com or namedirectory.com one of these 2 I m not sure where the logs are to find you the correct error, but today i did thsi install and not working so something is wrong

can you test please

and correct issue thanks so much

**Comment by spirogg** [comment]
error from my program:

File to convert: test.avi
Converted file: test.mp4
Command send to server: /usr/local/bin/ffmpeg -i test.avi -vcodec libx264 -s 640x360 -threads 4 -movflags faststart test.mp4
FFmpeg output
array(0) {
}
int(127)

**Comment by ninetian** [comment]
what is ai?

**Comment by spirogg** [comment]
Closing this issue. I deleted and reinstalled all ok. 

Sorry thanks.
